include: package:total_lints/app.yaml

linter:
  rules:
    prefer_relative_imports: false
    avoid_relative_lib_imports: true
    prefer_single_quotes: false
    prefer_double_quotes: true
    use_setters_to_change_properties: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    require_trailing_commas: true
